export interface ApprovedCommandDefinition {
  commandName: string;
  category: string;
  ownerRuntime: string;
  priority: 'P1' | 'P2' | 'P3' | 'P4';
  introducedInPhase: number;
}

export const approvedCommandManifest: ApprovedCommandDefinition[] = [
  {
    commandName: 'capital-contribution',
    category: 'activity',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'capital-raid',
    category: 'activity',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'clan-activity',
    category: 'activity',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'clan-games',
    category: 'activity',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'lastseen',
    category: 'activity',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'alias-create',
    category: 'alias',
    ownerRuntime: 'clashmate',
    priority: 'P3',
    introducedInPhase: 7,
  },
  {
    commandName: 'alias-delete',
    category: 'alias',
    ownerRuntime: 'clashmate',
    priority: 'P3',
    introducedInPhase: 7,
  },
  {
    commandName: 'alias-list',
    category: 'alias',
    ownerRuntime: 'clashmate',
    priority: 'P3',
    introducedInPhase: 7,
  },
  {
    commandName: 'autorole-clan-roles',
    category: 'autorole',
    ownerRuntime: 'clashmate',
    priority: 'P3',
    introducedInPhase: 7,
  },
  {
    commandName: 'autorole-config',
    category: 'autorole',
    ownerRuntime: 'clashmate',
    priority: 'P3',
    introducedInPhase: 7,
  },
  {
    commandName: 'autorole-disable',
    category: 'autorole',
    ownerRuntime: 'clashmate',
    priority: 'P3',
    introducedInPhase: 7,
  },
  {
    commandName: 'autorole-family',
    category: 'autorole',
    ownerRuntime: 'clashmate',
    priority: 'P3',
    introducedInPhase: 7,
  },
  {
    commandName: 'autorole-leagues',
    category: 'autorole',
    ownerRuntime: 'clashmate',
    priority: 'P3',
    introducedInPhase: 7,
  },
  {
    commandName: 'autorole-list',
    category: 'autorole',
    ownerRuntime: 'clashmate',
    priority: 'P3',
    introducedInPhase: 7,
  },
  {
    commandName: 'autorole-refresh',
    category: 'autorole',
    ownerRuntime: 'clashmate',
    priority: 'P3',
    introducedInPhase: 7,
  },
  {
    commandName: 'autorole-town-hall',
    category: 'autorole',
    ownerRuntime: 'clashmate',
    priority: 'P3',
    introducedInPhase: 7,
  },
  {
    commandName: 'nickname-config',
    category: 'autorole',
    ownerRuntime: 'clashmate',
    priority: 'P3',
    introducedInPhase: 7,
  },
  {
    commandName: 'nickname-refresh',
    category: 'autorole',
    ownerRuntime: 'clashmate',
    priority: 'P3',
    introducedInPhase: 7,
  },
  {
    commandName: 'category-create',
    category: 'category',
    ownerRuntime: 'clashmate',
    priority: 'P3',
    introducedInPhase: 7,
  },
  {
    commandName: 'category-delete',
    category: 'category',
    ownerRuntime: 'clashmate',
    priority: 'P3',
    introducedInPhase: 7,
  },
  {
    commandName: 'category-edit',
    category: 'category',
    ownerRuntime: 'clashmate',
    priority: 'P3',
    introducedInPhase: 7,
  },
  {
    commandName: 'category-list',
    category: 'category',
    ownerRuntime: 'clashmate',
    priority: 'P3',
    introducedInPhase: 7,
  },
  {
    commandName: 'config',
    category: 'config',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'debug',
    category: 'config',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'whitelist',
    category: 'config',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'post-clan-rules',
    category: 'custom',
    ownerRuntime: 'clashmate',
    priority: 'P3',
    introducedInPhase: 7,
  },
  {
    commandName: 'cwl-attacks',
    category: 'cwl',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'cwl-lineup',
    category: 'cwl',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'cwl-members',
    category: 'cwl',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'cwl-roster',
    category: 'cwl',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'cwl-round',
    category: 'cwl',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'cwl-stars',
    category: 'cwl',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'cwl-stats',
    category: 'cwl',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'flag-create',
    category: 'flag',
    ownerRuntime: 'clashmate',
    priority: 'P3',
    introducedInPhase: 7,
  },
  {
    commandName: 'flag-delete',
    category: 'flag',
    ownerRuntime: 'clashmate',
    priority: 'P3',
    introducedInPhase: 7,
  },
  {
    commandName: 'flag-list',
    category: 'flag',
    ownerRuntime: 'clashmate',
    priority: 'P3',
    introducedInPhase: 7,
  },
  {
    commandName: 'history',
    category: 'history',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'history-attack',
    category: 'history',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'history-capital-contribution',
    category: 'history',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'history-capital-raids',
    category: 'history',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'history-clan-games',
    category: 'history',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'history-cwl-attacks',
    category: 'history',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'history-donations',
    category: 'history',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'history-eos-trophies',
    category: 'history',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'history-join-leave',
    category: 'history',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'history-legend-attacks',
    category: 'history',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'history-loot',
    category: 'history',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'history-war-attack',
    category: 'history',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'leaderboard-capital',
    category: 'leaderboard',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'leaderboard-clans',
    category: 'leaderboard',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'leaderboard-players',
    category: 'leaderboard',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'legend-attacks',
    category: 'legend',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'legend-days',
    category: 'legend',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'legend-leaderboard',
    category: 'legend',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'legend-stats',
    category: 'legend',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'link-add',
    category: 'link',
    ownerRuntime: 'clashmate',
    priority: 'P1',
    introducedInPhase: 6,
  },
  {
    commandName: 'link-create',
    category: 'link',
    ownerRuntime: 'clashmate',
    priority: 'P1',
    introducedInPhase: 6,
  },
  {
    commandName: 'link-delete',
    category: 'link',
    ownerRuntime: 'clashmate',
    priority: 'P1',
    introducedInPhase: 6,
  },
  {
    commandName: 'link-list',
    category: 'link',
    ownerRuntime: 'clashmate',
    priority: 'P1',
    introducedInPhase: 6,
  },
  {
    commandName: 'profile',
    category: 'link',
    ownerRuntime: 'clashmate',
    priority: 'P1',
    introducedInPhase: 6,
  },
  {
    commandName: 'timezone',
    category: 'link',
    ownerRuntime: 'clashmate',
    priority: 'P1',
    introducedInPhase: 6,
  },
  {
    commandName: 'verify',
    category: 'link',
    ownerRuntime: 'clashmate',
    priority: 'P1',
    introducedInPhase: 6,
  },
  {
    commandName: 'blacklist',
    category: 'owner',
    ownerRuntime: 'clashmate',
    priority: 'P4',
    introducedInPhase: 7,
  },
  {
    commandName: 'feature-flags',
    category: 'owner',
    ownerRuntime: 'clashmate',
    priority: 'P4',
    introducedInPhase: 7,
  },
  {
    commandName: 'guild-ban',
    category: 'owner',
    ownerRuntime: 'clashmate',
    priority: 'P4',
    introducedInPhase: 7,
  },
  {
    commandName: 'suggestions',
    category: 'owner',
    ownerRuntime: 'clashmate',
    priority: 'P4',
    introducedInPhase: 7,
  },
  {
    commandName: 'usage',
    category: 'owner',
    ownerRuntime: 'clashmate',
    priority: 'P4',
    introducedInPhase: 7,
  },
  {
    commandName: 'reminders-config',
    category: 'reminders',
    ownerRuntime: 'clashmate',
    priority: 'P3',
    introducedInPhase: 7,
  },
  {
    commandName: 'reminders-create',
    category: 'reminders',
    ownerRuntime: 'clashmate',
    priority: 'P3',
    introducedInPhase: 7,
  },
  {
    commandName: 'reminders-delete',
    category: 'reminders',
    ownerRuntime: 'clashmate',
    priority: 'P3',
    introducedInPhase: 7,
  },
  {
    commandName: 'reminders-edit',
    category: 'reminders',
    ownerRuntime: 'clashmate',
    priority: 'P3',
    introducedInPhase: 7,
  },
  {
    commandName: 'reminders-list',
    category: 'reminders',
    ownerRuntime: 'clashmate',
    priority: 'P3',
    introducedInPhase: 7,
  },
  {
    commandName: 'reminders-now',
    category: 'reminders',
    ownerRuntime: 'clashmate',
    priority: 'P3',
    introducedInPhase: 7,
  },
  {
    commandName: 'army',
    category: 'search',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'attacks',
    category: 'search',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'boosts',
    category: 'search',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'caller',
    category: 'search',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'clan',
    category: 'search',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'clan-history',
    category: 'search',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'compo',
    category: 'search',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'donations',
    category: 'search',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'donations-range',
    category: 'search',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'layout-config',
    category: 'search',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'layout-post',
    category: 'search',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'lineup',
    category: 'search',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'members',
    category: 'search',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'player',
    category: 'search',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'remaining',
    category: 'search',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'rushed',
    category: 'search',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'search',
    category: 'search',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'stats',
    category: 'search',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'units',
    category: 'search',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'upgrades',
    category: 'search',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'war',
    category: 'search',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'warlog',
    category: 'search',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'clans',
    category: 'setup',
    ownerRuntime: 'clashmate',
    priority: 'P3',
    introducedInPhase: 7,
  },
  {
    commandName: 'setup-buttons',
    category: 'setup',
    ownerRuntime: 'clashmate',
    priority: 'P3',
    introducedInPhase: 7,
  },
  {
    commandName: 'setup-clan',
    category: 'setup',
    ownerRuntime: 'clashmate',
    priority: 'P3',
    introducedInPhase: 7,
  },
  {
    commandName: 'setup-clan-embed',
    category: 'setup',
    ownerRuntime: 'clashmate',
    priority: 'P3',
    introducedInPhase: 7,
  },
  {
    commandName: 'setup-clan-logs',
    category: 'setup',
    ownerRuntime: 'clashmate',
    priority: 'P3',
    introducedInPhase: 7,
  },
  {
    commandName: 'setup-events',
    category: 'setup',
    ownerRuntime: 'clashmate',
    priority: 'P3',
    introducedInPhase: 7,
  },
  {
    commandName: 'setup-list',
    category: 'setup',
    ownerRuntime: 'clashmate',
    priority: 'P3',
    introducedInPhase: 7,
  },
  {
    commandName: 'setup-server-logs',
    category: 'setup',
    ownerRuntime: 'clashmate',
    priority: 'P3',
    introducedInPhase: 7,
  },
  {
    commandName: 'setup-utility',
    category: 'setup',
    ownerRuntime: 'clashmate',
    priority: 'P3',
    introducedInPhase: 7,
  },
  {
    commandName: 'summary-activity',
    category: 'summary',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'summary-attacks',
    category: 'summary',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'summary-best',
    category: 'summary',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'summary-capital-contribution',
    category: 'summary',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'summary-capital-raids',
    category: 'summary',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'summary-clan-games',
    category: 'summary',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'summary-clans',
    category: 'summary',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'summary-compo',
    category: 'summary',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'summary-cwl-ranks',
    category: 'summary',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'summary-cwl-status',
    category: 'summary',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'summary-donations',
    category: 'summary',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'summary-leagues',
    category: 'summary',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'summary-missed-wars',
    category: 'summary',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'summary-trophies',
    category: 'summary',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'summary-war-results',
    category: 'summary',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'summary-wars',
    category: 'summary',
    ownerRuntime: 'clashmate',
    priority: 'P2',
    introducedInPhase: 7,
  },
  {
    commandName: 'ask',
    category: 'util',
    ownerRuntime: 'clashmate',
    priority: 'P1',
    introducedInPhase: 7,
  },
  {
    commandName: 'events',
    category: 'util',
    ownerRuntime: 'clashmate',
    priority: 'P1',
    introducedInPhase: 7,
  },
  {
    commandName: 'help',
    category: 'util',
    ownerRuntime: 'clashmate',
    priority: 'P1',
    introducedInPhase: 7,
  },
  {
    commandName: 'invite',
    category: 'util',
    ownerRuntime: 'clashmate',
    priority: 'P1',
    introducedInPhase: 7,
  },
  {
    commandName: 'ping',
    category: 'util',
    ownerRuntime: 'clashmate',
    priority: 'P1',
    introducedInPhase: 7,
  },
  {
    commandName: 'status',
    category: 'util',
    ownerRuntime: 'clashmate',
    priority: 'P1',
    introducedInPhase: 7,
  },
];

export const approvedCommandCount = 126;

export const approvedCommandCategoryCounts: Record<string, number> = {
  'activity': 5,
  'alias': 3,
  'autorole': 10,
  'category': 4,
  'config': 3,
  'custom': 1,
  'cwl': 7,
  'flag': 3,
  'history': 12,
  'leaderboard': 3,
  'legend': 4,
  'link': 7,
  'owner': 5,
  'reminders': 6,
  'search': 22,
  'setup': 9,
  'summary': 16,
  'util': 6,
};
